### PR TITLE
Document `use_lxd`

### PR DESCRIPTION
**Pull request by casperdcl**
Somehow missing from merge of #4

### CODE REVIEW

**Comment by casperdcl** [comment]
oops done already (duplicate)

**Comment by casperdcl** [comment]
This PR just updates the version number to the latest tag for using the latest features.

**Comment by samuelmeuli** [comment]
This shouldn't be necessary. I'm following [GitHub's recommended versioning approach](https://github.com/actions/toolkit/blob/master/docs/action-versioning.md). Using `@v1` instead of `@v1.1.0` allows users to continue to receive fixes.

**Comment by casperdcl** [comment]
Ah

> Move the major version tag (v1, v2, etc.) to point to the ref of the current release

They actually want us to force-push the `v1` tag. Yuck.

**Pull request closed without merging**
